version: '3'
services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_VOLUME}/.portainer/config:/data
    restart: always
    network_mode: host
  sonarr:
    image: linuxserver/sonarr
    container_name: "sonarr"
    volumes:
      - ${CONFIG_VOLUME}/.sonarr/config:/config
      - ${DATA_VOLUME}/downloads:/downloads
      - ${DATA_VOLUME}/tv:/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    volumes:
      - ${CONFIG_VOLUME}/.transmission/config:/config
      - ${VOLUME}/downloads:/downloads
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ${CONFIG_VOLUME}/.jackett/config:/config
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: always
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ${CONFIG_VOLUME}/.radarr/config:/config
      - ${DATA_VOLUME}/downloads:/downloads
      - ${DATA_VOLUME}/movies:/movies
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    volumes: 
      - ${CONFIG_VOLUME}/.duplicati/config:/config
      - ${CONFIG_VOLUME}:/source
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  plex:
    network_mode: host
    image: linuxserver/plex
    container_name: plex
    volumes:
      - ${CONFIG_VOLUME}/.plex/config:/config
      - ${DATA_VOLUME}/movies:/movies
      - ${DATA_VOLUME}/tv:/tv
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
     - ${CONFIG_VOLUME}/.bazarr/config:/config
     - ${DATA_VOLUME}/tv:/tv
     - ${DATA_VOLUME}/movies:/movies
    restart: unless-stopped
    network_mode: service:vpn
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=dcop.duckdns.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ${CONFIG_VOLUME}/.wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 28150:51820/udp
    restart: unless-stopped
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_VOLUME}/.heimdall/config:/config
    ports:
      - 8090:80
      - 4343:443
    restart: unless-stopped
